server:
  port: 0

spring:
  application:
    name: 2st-service

eureka:
  instance:
    instance-id: #{spring.applicatoin.name}:${spring.application.isntance_id:${}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka