server:
  port: 8000

eureka:
    client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: 1st-service-get
#          uri: http://localhost:58213/
          uri: lb://1ST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}

        - id: 2nd-service-get
#          uri: http://localhost:12345/
          uri: lb://2ND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}